### ISSUE TITLE
v2: status bar padding is not added to iOS app in view

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-view-issues#164]
The status bar padding is added via the platform registry when it is an ios and cordova app:

https://github.com/driftyco/ionic/blob/2.0/ionic/platform/registry.ts#L105

This isn't working when viewed from Ionic View. For anyone that runs into this, the workaround is to set it in the config:

```
@App({
  templateUrl: 'build/app.html',
  config: {
    platforms: {
      ios: {
        statusbarPadding: true
      }
    }
  }
})
```

**Comment by AdrianTeh** [comment]
@brandyscarney Thanks, it works on iOS device, but how can I not show the padding on browser platform?

**Comment by brandyscarney** [comment]
This could be solved in the ios version by adding `?ionicStatusbarPadding=true` to the URL.

**Comment by jcelliott** [comment]
Looks like this doesn't work on the latest ionic. All the example starter apps use `@Component` instead of `@App` and the [config docs](http://ionicframework.com/docs/v2/api/config/Config/) don't mention `statusbarPadding`.

**Comment by brandyscarney** [comment]
The `config` is passed in the `ionicBootstrap` now, like this:

```
ionicBootstrap(ConferenceApp, [ConferenceData, UserData], {
  tabbarPlacement: 'bottom',
  statusbarPadding: true
});
```

The property just needs to be added to the config documentation, but it should still work.

**Comment by slaughac** [comment]
statusbarPadding still does not work in Ionic View.  It works when testing in browser, just doesn't work with Ionic View app.

**Comment by jcelliott** [comment]
@brandyscarney thanks!

@slaughac passing the config in `ionicBootstrap` worked for me in the Ionic View app.

**Comment by brandyscarney** [comment]
Just to update: this issue has been fixed locally but isn't released yet. We plan on releasing a new version of Ionic View with this fix to the app store soon.

**Comment by j-zielinski** [comment]
@brandyscarney Any progress on this one, guys? We still have this issue on RC.0 in views with tabs/segments. Adding `{statusPadding: true}` doesn't fix problem :(

**Comment by royipressburger** [comment]
Im also seeing this issue with rc4. on web and on device.

**Comment by luigiinred** [comment]
I have been having this issue too.

`{statusPadding: true}` fixes the issue on iOS but also adds the padding to android
`{ios:{statusPadding: true}}` doesn't work 

It looks like it doesn't know what device I'm using.
` Device.platform` returns`{}`

**Comment by leroygumede** [comment]
app.Module.ts

```
    imports: [
        ChartModule,
        IonicModule.forRoot(MyApp, {
            tabsHideOnSubPages: true,
            platforms: {
                ios: {
                    statusbarPadding: true,
                }
            }
        })
    ],
```

Does not work

**Comment by francorafael** [comment]
in app.component.ts set this.statusBar.overlaysWeb to false

 initializeApp() {
    
    this.platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      this.statusBar.overlaysWebView(false);
      this.statusBar.styleDefault();
      this.splashScreen.hide();
    });
  }

**Comment by ajaysaini95700** [comment]
i am facing status bar problem. when i open app it is showing content below status bar refer screenshot before.png . but after open 3rd party app like facebook or whatsapp for sending data then after cancel  or successful, status bar show on top of content it is move to top refer screenshot  after.png
![before](https://user-images.githubusercontent.com/18483093/28159396-6a066f7c-67da-11e7-86e4-f6ef75483acf.png)
![after](https://user-images.githubusercontent.com/18483093/28159401-6d7f2edc-67da-11e7-83fa-eff006dffa9e.png)
currently i am using this code 
initializeApp() {

this.platform.ready().then(() => {
  // Okay, so the platform is ready and our plugins are available.
  // Here you can do any higher level native things you might need.
  this.statusBar.overlaysWebView(false);
  this.statusBar.styleDefault();
  this.splashScreen.hide();
});
}

but still facing this issue. please give me any solution

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
