### ISSUE TITLE
v2: two status bar issues + steps to reproduce

### ISSUE THREAD

**Issue by mtoo020** [ionic-team/ionic-view-issues#181]
1. If an app in ionic view hides the status bar, ionic view does not show the statusbar again when you close the app. So if you open another app in ionic view afterwards, unless that app explicitly tells the statusbar to show, it remains hidden.
2. Unless a previous app in ionic view has hidden the status bar, the status bar does not correctly overlay the webview when asked to. It overlays with a translucent background rather than transparent (in iOS).

To reproduce:
1. `ionic start show` and `ionic start hide` 
2.  In the window.Statusbar if statement, in hide add `StatusBar.hide();` and in show add:
   `StatusBar.styleLightContent();
   StatusBar.overlaysWebView(true);
   StatusBar.show();`
3. In show, also change the `ion-nav-bar` class to `bar-positive`.
4. `ionic upload` both and open ionic view 2.
5. Open show.
   Expected behaviour is a transparent statusbar over the blue nav bar.
   Actual behaviour is a translucent statusbar over the blue nav bar.
6. Open hide, then close it. Notice how the status bar remains hidden in ionic view.
7. Open show. Notice how the statusbar is transparent now.
8. Comment out `StatusBar.show();` in show, upload and open hide then show.
   Notice how the statusbar remains hidden when you open show.

Thank you for looking into this :)

**Comment by tlancina** [comment]
Hey this should be fixed in the latest release of View for iOS (1.1.1), let me know if it's not and I can re-open, thanks!

**Comment by mtoo020** [comment]
Hey Tim, thanks for the update. The second problem isn't yet fixed:

2. Unless a previous app in ionic view has hidden the status bar, the status bar does not correctly overlay the webview when asked to. It overlays with a translucent background rather than transparent (in iOS).

To reproduce:

1. `ionic start show`
2.  In the window.Statusbar if statement, add:
`StatusBar.styleLightContent();
 StatusBar.overlaysWebView(true);`
3. Also change the `ion-nav-bar` class to `bar-positive`.
4. `ionic upload` and open in ionic view 2.
Expected behaviour is a transparent statusbar over the blue nav bar.
Actual behaviour is a translucent statusbar over the blue nav bar.

Thank you for looking into this :)

**Comment by tlancina** [comment]
Hey thanks for the issue! With Ionic Pro we’re consolidating our support, so please head over to http://support.ionicjs.com if you’re having problems, thanks!
